name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_USERNAME: bloodnighttw
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: deploy
      run: 
        mvn --settings settings.xml deploy
    - name: Build with Maven
      run: 
        mvn -B package --file pom.xml
